# Generated by Django 5.1.1 on 2025-05-27 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnouncementTitel', models.CharField(default='NA', max_length=200)),
                ('Announcement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserAccess', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Accounts', 'Accounts'), ('Project Manager', 'Project Manager'), ('Employe', 'Employe')], default='Probation', max_length=20)),
                ('FirstName', models.CharField(default='NA', max_length=20)),
                ('LastName', models.CharField(default='NA', max_length=20)),
                ('Email', models.CharField(default='NA', max_length=100)),
                ('Designation', models.CharField(default='NA', max_length=50)),
                ('PermanentAddress', models.CharField(default='NA', max_length=200)),
                ('PresentAddress', models.CharField(default='NA', max_length=200)),
                ('PhoneNumbe', models.CharField(default='NA', max_length=50)),
                ('EmergencyPhoneNumber', models.CharField(default='NA', max_length=50)),
                ('Salary', models.CharField(default='NA', max_length=20)),
                ('JoiningDate', models.CharField(default='NA', max_length=50)),
                ('PermanencyDate', models.CharField(default='NA', max_length=50)),
                ('Image', models.ImageField(default='static/user/avater.webp', upload_to='media/user/profile/')),
                ('BankName', models.CharField(default='NA', max_length=100)),
                ('BankAccountName', models.CharField(default='NA', max_length=100)),
                ('BankAccountNumber', models.CharField(default='NA', max_length=100)),
                ('BankBranchName', models.CharField(default='NA', max_length=100)),
                ('BankSwiftCode', models.CharField(default='NA', max_length=100)),
                ('BankRoutingNumber', models.CharField(default='NA', max_length=100)),
                ('BankPhoneNumber', models.CharField(default='NA', max_length=100)),
                ('NIDNumber', models.CharField(default='NA', max_length=20)),
                ('TINNumber', models.CharField(default='NA', max_length=20)),
                ('FatherName', models.CharField(default='NA', max_length=20)),
                ('MotherName', models.CharField(default='NA', max_length=20)),
                ('EmployeStatus', models.CharField(choices=[('Probation', 'Probation'), ('Permanent', 'Permanent')], default='Probation', max_length=20)),
                ('AppointmentLetter', models.FileField(null=True, upload_to='media/user/AppointmentLetter/')),
                ('NDA', models.FileField(null=True, upload_to='media/user/NDA/')),
                ('SalaryIncrementLetter', models.FileField(null=True, upload_to='media/user/NDA/')),
                ('PromotionLetter', models.FileField(null=True, upload_to='media/user/PromotionLetter/')),
                ('UserStatus', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
