# Generated by Django 5.1.1 on 2025-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserAccess',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Accounts', 'Accounts'), ('Project Manager', 'Project Manager'), ('Employe', 'Employe')], default='Employe', max_length=20),
        ),
    ]
