# Generated by Django 5.1.1 on 2025-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_userprofile_useraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(default='', max_length=200)),
                ('LeaveType', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave')], default='NA', max_length=20)),
                ('SubmitionDate', models.CharField(default='NA', max_length=50)),
                ('Massage', models.TextField()),
                ('HR_approval', models.BooleanField(default=False)),
                ('PM_approval', models.BooleanField(default=False)),
                ('MD_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='UserAccess',
            field=models.CharField(choices=[('Employe', 'Employe'), ('Admin', 'Admin'), ('HR', 'HR'), ('Accounts', 'Accounts'), ('Project Manager', 'Project Manager')], default='Employe', max_length=20),
        ),
    ]
