# Generated by Django 5.1.1 on 2025-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_leave_applications_name_leave_applications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_applications',
            name='Subject',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
