# Generated by Django 5.1.1 on 2025-07-22 20:11

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_leave_applications_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='AnnouncementTitel',
        ),
        migrations.AddField(
            model_name='announcement',
            name='Titel',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Announcement',
            field=tinymce.models.HTMLField(),
        ),
    ]
