# Generated by Django 5.1.1 on 2025-07-22 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_announcement_announcementtitel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 2, 16, 29, 309648)),
        ),
    ]
