# Generated by Django 5.1.1 on 2025-07-22 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_announcement_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 2, 18, 47, 753886)),
        ),
    ]
