# Generated by Django 5.1.1 on 2025-07-24 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_announcement_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_applications',
            name='FromDate',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='leave_applications',
            name='ToDate',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 25, 0, 35, 56, 625693)),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='LeaveType',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='SubmitionDate',
            field=models.CharField(default=datetime.datetime(2025, 7, 25, 0, 35, 56, 625693), max_length=50),
        ),
    ]
