# Generated by Django 5.1.1 on 2025-07-25 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_leave_applications_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_applications',
            name='HR_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave_applications',
            name='MD_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave_applications',
            name='PM_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 25, 18, 10, 33, 615531)),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='SubmitionDate',
            field=models.CharField(default=datetime.datetime(2025, 7, 25, 18, 10, 33, 615531), max_length=50),
        ),
    ]
