# Generated by Django 5.1.1 on 2025-07-25 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_leave_applications_hr_reject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_applications',
            name='Document',
            field=models.FileField(null=True, upload_to='media/user/LeaveApplication/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 25, 19, 8, 8, 444298)),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='SubmitionDate',
            field=models.CharField(default=datetime.datetime(2025, 7, 25, 19, 8, 8, 444298), max_length=50),
        ),
    ]
