# Generated by Django 5.1.1 on 2025-07-25 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_leave_applications_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 26, 2, 12, 26, 47426)),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='SubmitionDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 26, 2, 12, 26, 42489), max_length=50),
        ),
    ]
