# Generated by Django 5.1.1 on 2025-07-31 15:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_announcement_post_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 31, 21, 37, 38, 696561)),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='SubmitionDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 31, 21, 37, 38, 695560), max_length=50),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(default='', max_length=50)),
                ('Prayer_Break', models.CharField(default=0, max_length=20)),
                ('Dinner_Break', models.CharField(default=0, max_length=20)),
                ('Tea_Break', models.CharField(default=0, max_length=20)),
                ('Signing_In_Time', models.CharField(default=0, max_length=20)),
                ('Signing_Out_Time', models.CharField(default=0, max_length=20)),
                ('Date', models.DateField(default=datetime.datetime(2025, 7, 31, 21, 37, 38, 697561))),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
