# Generated by Django 5.1.1 on 2025-07-31 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_announcement_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Company',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Post_Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 31, 21, 46, 53, 393982)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 7, 31, 21, 46, 53, 409852)),
        ),
        migrations.AlterField(
            model_name='leave_applications',
            name='SubmitionDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 31, 21, 46, 53, 393982), max_length=50),
        ),
    ]
